// Code generated by protoc-gen-go. DO NOT EDIT.
// source: playpb/play.proto

package playpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResourceType int32

const (
	ResourceType_UNKNOWN       ResourceType = 0
	ResourceType_WP_ENTRYPOINT ResourceType = 1
	ResourceType_CSL_CLUSTER   ResourceType = 2
)

var ResourceType_name = map[int32]string{
	0: "UNKNOWN",
	1: "WP_ENTRYPOINT",
	2: "CSL_CLUSTER",
}

var ResourceType_value = map[string]int32{
	"UNKNOWN":       0,
	"WP_ENTRYPOINT": 1,
	"CSL_CLUSTER":   2,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}

func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e1e9ae7fb31743f7, []int{0}
}

type Token struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	SpClientId           []byte   `protobuf:"bytes,2,opt,name=sp_client_id,json=spClientId,proto3" json:"sp_client_id,omitempty"`
	SpClientSecret       []byte   `protobuf:"bytes,3,opt,name=sp_client_secret,json=spClientSecret,proto3" json:"sp_client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e9ae7fb31743f7, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *Token) GetSpClientId() []byte {
	if m != nil {
		return m.SpClientId
	}
	return nil
}

func (m *Token) GetSpClientSecret() []byte {
	if m != nil {
		return m.SpClientSecret
	}
	return nil
}

type Token2 struct {
	ProjectId            []byte       `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ResourceType         ResourceType `protobuf:"varint,2,opt,name=resourceType,proto3,enum=ResourceType" json:"resourceType,omitempty"`
	ResourceId           string       `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	SpClientId           []byte       `protobuf:"bytes,4,opt,name=sp_client_id,json=spClientId,proto3" json:"sp_client_id,omitempty"`
	SpClientSecret       []byte       `protobuf:"bytes,5,opt,name=sp_client_secret,json=spClientSecret,proto3" json:"sp_client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Token2) Reset()         { *m = Token2{} }
func (m *Token2) String() string { return proto.CompactTextString(m) }
func (*Token2) ProtoMessage()    {}
func (*Token2) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e9ae7fb31743f7, []int{1}
}

func (m *Token2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token2.Unmarshal(m, b)
}
func (m *Token2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token2.Marshal(b, m, deterministic)
}
func (m *Token2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token2.Merge(m, src)
}
func (m *Token2) XXX_Size() int {
	return xxx_messageInfo_Token2.Size(m)
}
func (m *Token2) XXX_DiscardUnknown() {
	xxx_messageInfo_Token2.DiscardUnknown(m)
}

var xxx_messageInfo_Token2 proto.InternalMessageInfo

func (m *Token2) GetProjectId() []byte {
	if m != nil {
		return m.ProjectId
	}
	return nil
}

func (m *Token2) GetResourceType() ResourceType {
	if m != nil {
		return m.ResourceType
	}
	return ResourceType_UNKNOWN
}

func (m *Token2) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *Token2) GetSpClientId() []byte {
	if m != nil {
		return m.SpClientId
	}
	return nil
}

func (m *Token2) GetSpClientSecret() []byte {
	if m != nil {
		return m.SpClientSecret
	}
	return nil
}

func init() {
	proto.RegisterEnum("ResourceType", ResourceType_name, ResourceType_value)
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*Token2)(nil), "Token2")
}

func init() { proto.RegisterFile("playpb/play.proto", fileDescriptor_e1e9ae7fb31743f7) }

var fileDescriptor_e1e9ae7fb31743f7 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0xc3, 0x30,
	0x1c, 0xc6, 0xed, 0xe6, 0x26, 0xfb, 0xaf, 0x9b, 0x5d, 0x4e, 0xbb, 0x88, 0xa5, 0x78, 0x28, 0x82,
	0x2d, 0xce, 0x07, 0x10, 0x2c, 0x3b, 0x14, 0x47, 0x37, 0xd2, 0x8e, 0xa1, 0x97, 0xb2, 0xa6, 0x41,
	0xeb, 0x6a, 0x13, 0x92, 0xf4, 0xb0, 0x27, 0xf4, 0xb5, 0xa4, 0x71, 0xc5, 0x09, 0x3b, 0x78, 0x0a,
	0xf9, 0xf1, 0x23, 0x5f, 0x3e, 0x3e, 0x98, 0xf0, 0x72, 0xbb, 0xe7, 0x99, 0xdf, 0x1c, 0x1e, 0x17,
	0x4c, 0x31, 0x47, 0x40, 0x2f, 0x61, 0x3b, 0x5a, 0xa1, 0x2b, 0x00, 0x52, 0xd6, 0x52, 0x51, 0x91,
	0x16, 0xf9, 0xd4, 0xb0, 0x0d, 0x77, 0x80, 0x07, 0x07, 0x12, 0xe6, 0xc8, 0x06, 0x53, 0xf2, 0x94,
	0x94, 0x05, 0xad, 0x54, 0x23, 0x74, 0x6c, 0xc3, 0x35, 0x31, 0x48, 0x1e, 0x68, 0x14, 0xe6, 0xc8,
	0x05, 0xeb, 0xd7, 0x90, 0x94, 0x08, 0xaa, 0xa6, 0x5d, 0x6d, 0x8d, 0x5b, 0x2b, 0xd6, 0xd4, 0xf9,
	0x32, 0xa0, 0xaf, 0x43, 0x67, 0x4d, 0x2a, 0x17, 0xec, 0x83, 0x12, 0xd5, 0xa6, 0x9a, 0x78, 0x70,
	0x20, 0x61, 0x8e, 0xee, 0xc1, 0x14, 0x54, 0xb2, 0x5a, 0x10, 0x9a, 0xec, 0x39, 0xd5, 0xa9, 0xe3,
	0xd9, 0xc8, 0xc3, 0x47, 0x10, 0xff, 0x51, 0xd0, 0x35, 0x0c, 0xdb, 0x7b, 0xf3, 0x64, 0x57, 0x17,
	0x81, 0x16, 0x9d, 0x68, 0x72, 0xfe, 0xaf, 0x26, 0xbd, 0x53, 0x4d, 0x6e, 0x1f, 0xc1, 0x3c, 0xfe,
	0x0a, 0x1a, 0xc2, 0xc5, 0x3a, 0x7a, 0x8e, 0x96, 0x9b, 0xc8, 0x3a, 0x43, 0x13, 0x18, 0x6d, 0x56,
	0xe9, 0x3c, 0x4a, 0xf0, 0xcb, 0x6a, 0x19, 0x46, 0x89, 0x65, 0xa0, 0x4b, 0x18, 0x06, 0xf1, 0x22,
	0x0d, 0x16, 0xeb, 0x38, 0x99, 0x63, 0xab, 0xf3, 0x74, 0xf3, 0xea, 0xbc, 0x15, 0xea, 0xbd, 0xce,
	0x3c, 0xc2, 0x3e, 0xfd, 0x6c, 0x5b, 0xed, 0xa4, 0xaf, 0x87, 0xb9, 0x6b, 0x36, 0xf2, 0x7f, 0xf6,
	0xca, 0xfa, 0x1a, 0x3d, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x30, 0xc4, 0xa3, 0x26, 0xc0, 0x01,
	0x00, 0x00,
}
